name: Update README with WakaTime stats

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 00:00 UTC 自动更新
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: WakaTime Readme
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
